enum Environment {
  DIRECTORY_MUSIC,
  DIRECTORY_PODCASTS,
  DIRECTORY_RINGTONES,
  DIRECTORY_ALARMS,
  DIRECTORY_NOTIFICATIONS,
  DIRECTORY_PICTURES,
  DIRECTORY_MOVIES,
  DIRECTORY_DOWNLOADS,
  DIRECTORY_DCIM,
  DIRECTORY_DOCUMENTS,
  DIRECTORY_SCREENSHOTS,
  DIRECTORY_AUDIOBOOKS
}

const String dirMUSIC = 'DIRECTORY_MUSIC';
const String dirPODCASTS = 'DIRECTORY_PODCASTS';
const String dirRINGTONES = 'DIRECTORY_RINGTONES';
const String dirALARMS = 'DIRECTORY_ALARMS';
const String dirNOTIFICATIONS = 'DIRECTORY_NOTIFICATIONS';
const String dirPICTURES = 'DIRECTORY_PICTURES';
const String dirMOVIES = 'DIRECTORY_MOVIES';
const String dirDOWNLOADS = 'DIRECTORY_DOWNLOADS';
const String dirDCIM = 'DIRECTORY_DCIM';
const String dirDOCUMENTS = 'DIRECTORY_DOCUMENTS';
const String dirSCREENSHOTS = 'DIRECTORY_SCREENSHOTS';
const String dirAUDIOBOOKS = 'DIRECTORY_AUDIOBOOKS';
